export const PLAN_CONFIG = {
  free: {
    name: 'Free Forever',
    slug: 'free' as const,
    tagline: 'Start Selling at No Cost',
    price: { monthly: 0, yearly: 0 },
    commissionRate: 8,
    productLimit: 6,
    features: [
      'Free online store',
      'Up to 6 product listings',
      'Order management dashboard',
      'Secure payment withdrawal',
      'Standard delivery options',
      'Basic sales reports',
      'Customer reviews & ratings',
      'Access to Vendorspot promotions',
      'Store sharing tools',
      'Basic inventory management',
    ],
    badge: 'Free Plan',
    badgeColor: '#F59E0B',
    paystackPlanCode: { monthly: null as null, yearly: null as null },
  },
  growth: {
    name: 'Growth Plan',
    slug: 'growth' as const,
    tagline: 'Grow Faster & Sell Smarter',
    price: { monthly: 2500, yearly: 25000 },
    commissionRate: 6,
    productLimit: null as null,
    features: [
      'Everything in Free Plan, plus:',
      'Unlimited product listings',
      'AI product title generation',
      'AI product description generation',
      'Store customization',
      'Advanced inventory management',
      'Sales analytics dashboard',
      'Customer insights',
      'Product performance tracking',
      'Chat customers directly on active orders',
      'Multiple pickup addresses',
      'Invoicing tools',
      'Downloadable financial statements',
      'Priority customer support',
      'Featured store opportunities',
      'Marketing and promotional campaigns',
      'Social media sharing tools',
      'Access to vendor training resources',
      'Access to business grants',
    ],
    badge: 'Growth Plan',
    badgeColor: '#3B82F6',
    paystackPlanCode: {
      monthly: process.env.PAYSTACK_GROWTH_MONTHLY_CODE || '',
      yearly: process.env.PAYSTACK_GROWTH_YEARLY_CODE || '',
    },
  },
  pro: {
    name: 'Pro Plan',
    slug: 'pro' as const,
    tagline: 'Built for Serious Businesses',
    price: { monthly: 5000, yearly: 50000 },
    commissionRate: 5,
    productLimit: null as null,
    features: [
      'Everything in Growth Plan, plus:',
      'Trust Tick Badge',
      'Homepage featured store placement',
      'Featured product placement',
      'Priority search ranking',
      'Advanced business analytics',
      'Revenue forecasting insights',
      'Customer lifetime value tracking',
      'Premium financial reporting',
      'Dedicated account manager',
      'Priority dispute resolution',
      'Special delivery for high-value products',
      'Video product post',
      'Team management account',
      'Early access to new features',
      'Premium advertising credits',
      'Marketplace growth consultation',
      'Exclusive seller community access',
      'Multi-user staff access',
    ],
    badge: 'Pro Plan',
    badgeColor: '#10B981',
    paystackPlanCode: {
      monthly: process.env.PAYSTACK_PRO_MONTHLY_CODE || '',
      yearly: process.env.PAYSTACK_PRO_YEARLY_CODE || '',
    },
  },
} as const;

export type PlanSlug = keyof typeof PLAN_CONFIG;

export const getPlanConfig = (plan: PlanSlug) => PLAN_CONFIG[plan];
export const getProductLimit = (plan: PlanSlug): number | null => PLAN_CONFIG[plan].productLimit;
export const getCommissionRate = (plan: PlanSlug): number => PLAN_CONFIG[plan].commissionRate;
